// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frdyixpjtunzllewusfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyZHlpeHBqdHVuemxsZXd1c2ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MzcyODAsImV4cCI6MjA3NDExMzI4MH0.RAObK79xc4yetIgnyHVmbJjtKofjk921CfTeYIJbQZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});